name: DEPLOY TO STAGING

on:
    pull_request:
        types : [closed]
        branches:
            - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: "ec2-3-22-168-254.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/survey-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "ubuntu"
        with:
          hosts: "ubuntu@ec2-3-22-168-254.us-east-2.compute.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/survey-backend
            npm install
            sudo systemctl restart survey-backend
